### ISSUE TITLE
DPL-322 Show correct set of labware in "Work in progress view"

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1030]
**User story**
As a member of the lab teams, I want to be able to visualise the 'in progress' labware in a kanban-style view, so that I can manage my workload and make sure all plates are processed that need to be. 

**Who are the primary contacts for this story** 
Katy

**Who is the nominated tester for UAT**
We will have to recruit one or two SSRs and lab team leads to help with UAT - checking the correct set of labware is present

**Acceptance criteria**
Existing 'in progress' views are adapted as follows:
- [ ] If I cancel or fail a plate, it should no longer show in the view
- [ ] Labware that are not part of the relevant pipeline should not show (e.g. Lib Pool Norm tubes)
- [ ] Norm tubes that are not yet connected to a parent should not show (floating tubes are created upfront at the same time as the requests, but not connected up to the chain of labware until the end)
- [ ] This can be tested by checking the labware on the list retrieved against the labware on the SSRs' WIP spreadsheets (in collaboration with them)

**Additional context**

The result doesn't need to be perfect. If more issues are uncovered to do with the set of labware that is retrieved, a judgement call can be made whether the fixes can be included in this story or a new one.

Existing kanban views are at `/pipeline_work_in_progress/<pipeline name>`, and the code at `pipeline_work_in_progress_controller.rb`

Implementation suggestion: Change the query to filter based on request type - this should enable acceptance criteria 1 & 2.

**Comment by KatyTaylor** [comment]
Update: I re-worded this story to be generic rather than Heron-specific. Pasting the previous comment about business value for Heron below:

> The team currently use Trello to fulfil this requirement. Replacing this with a view in the LIMS removes the need to create the cards manually, saving time and reducing user error, as well as potential for closer integration with other functionality in the LIMS.
> This story will not completely remove the need for the Trello board as it is also used for data storage, so must be done in conjunction with other stories in the "Plate tracking" epic.

**Comment by SujitDey2022** [comment]
Need to check with Katy T. again on the scope of work
