### ISSUE TITLE
DPL-324 Show comments from ancestor labware [C=M, V=3]

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1033]
**User story**
As a Heron or DNAP user of Limber, when looking at the comments against a labware, I would also like to see comments from ancestor labware, because some comments are relevant to the whole line of related labware. 

Comments are useful for recording ad hoc information that doesn't fit in any particular field, such as unusual things that have happened to that plate or its ancestors.

**Who are the primary contacts for this story**
Sara, Liz E, Katy

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] On the page for a labware in Limber, I can see comments against all ancestor labware as well as against this one.
- [ ] When looking at comments, I can tell which ones are against this particular labware.
- [ ] Arrange notice / basic training for lab staff to encourage uptake of this feature (as it could be useful immediately).

**Additional context**
This is inspired by the way the lab teams use Trello currently - they drag a single card across columns to track its progress through a pipeline - and so any data recorded against it is visible throughout the process. This is in contrast to how the LIMS works, as we create a new record each time a new labware is created that needs to be tracked - so information is generally only accessible against one particular labware.

This is part of the 'Plate tracking' epic aimed at removing the use of Trello and paperwork in the Heron and DNAP lab teams. This is one building block. Hopefully it can become immediately useful, but other stories in the epic will need to be done to completely replace the Trello board / paperwork.

**Comment by stevieing** [comment]
Closed as Heron.
