### ISSUE TITLE
DPL-326 Use RT-Q plate for 'input barcode' instead of HT plate [C=M, V=3]

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1035]
**User story**
As a Heron lab user I would like the consistent identifier ('input plate barcode') down the pipeline to be the barcode of the LTHR RT-Q plate rather than of the LTHR Cherrypick ('HT' prefix) plate. This identifier is shown on barcode labels, on the labware page, and on the cards in the 'work in progress' (kanban) view. 

Currently, 1 of 4 Cherrypick barcodes is used, and it's not obvious to the user which one it will be. If the RT-Q plate barcode is used, it provides a more intuitive link to all the downstream plates and also the 4 parent Cherrypick plates.

**Who are the primary contacts for this story**
Sara, Katy

**Acceptance criteria**
RT-Q (or RT where used instead) plate barcode shown instead of the LTHR Cherrypick plate in following locations:
- [ ] Labware page
- [ ] Barcode labels
- [ ] Cards in work in progress view
- [ ] Root of summary page in Sequencescape (e.g. should /plate_summaries/HT-138151 be /plate_summaries/DN944643J ?)
- [ ] Are there any others...?
