### ISSUE TITLE
DPL-327 Find all plates associated with reagent batch [C=?, V=4]

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1036]
N.B. This story will need some research as to the best way to do this.

**User story**
As a Heron team lead, I would like to be able to easily find all labware associated with a specific reagent batch, and also the batch associated with a specific labware (both directions). This is useful for investigating and resolving problems associated with batches. 

**Who are the primary contacts for this story**
Barbora, Katy

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] I can find all labware associated with a positive or negative control batch 
- [ ] I can find all labware associated with an Artic plate batch
- [ ] I can find all labware associated with an tag plate batch 
- [ ] Given a labware, I can find which reagent batches (positive or negative control, Artic plate, tag plate) are associated with it

**Additional context**
Emma G thinks work around recording hierarchies of reagent batches has potential to be useful for other DNAP teams as well, e.g. High Throughput and Sample Management.

For Heron, batches are made in house, and ids for them are created using a spreadsheet, manually written onto the labware, and recorded against Trello cards and on the paper worksheet. This story is currently quite open, and could include generating batch barcodes as well as recording them in a searchable way in Limber. Related parts of the LIMS to consider are:
- Mixtio (used in CGaP)
- PhiX functionality in Sequencescape
- Tag plate functionality in Gatekeeper, Sequencescape and Limber

**Comment by TWJW-SANGER** [comment]
I think the acceptance criteria should include "given a labware identifier find the associated positive or negative control batch"  ?

To clarify, is this any labware in the pipeline or a specific plate at a specific point of the pipeline?

**Comment by JamesGlover** [comment]
See https://github.com/sanger/General-Backlog-Items/issues/89 for similar story

**Comment by JamesGlover** [comment]
We have means of recording arbitrary (key-value pair) metadata against labware in limber, so as an incredibly simple MVP we just allow barcodes to be scanned in and recorded agains the plates. Plate metadata is already visible in SS, and *I think* limber, but I don't think we currently have a mechanism, in place for lookup based on metadata.

Mixtio is already designed for reagent tracking

**Comment by JamesGlover** [comment]
We already track which PhiX was used, and this information *is* accessible through the lims, so that bit might just be a case of showing people how to get what they need, or improving the access to that data.

**Comment by JamesGlover** [comment]
Alos, tag plate information is already tracked, so again, that is probably just either showing people where to go for the data, or improving the accessibility of that.

**Comment by KatyTaylor** [comment]
> We have means of recording arbitrary (key-value pair) metadata against labware in limber, so as an incredibly simple MVP we just allow barcodes to be scanned in and recorded agains the plates. Plate metadata is already visible in SS, and _I think_ limber, but I don't think we currently have a mechanism, in place for lookup based on metadata.

Ah I didn't know this - where is it possible to do this? We had this story - https://github.com/sanger/limber/issues/1034 - already scoped out as potentially useful for recording various bits of data... but maybe something halfway there already exists?

**Comment by JamesGlover** [comment]
Its mostly the back-end stuff at the moment, used by the robots etc. for recording which one they were run on. So it should just be the interface side of things, and probably a bit of glue to help stick it all together.

**Comment by KatyTaylor** [comment]
> I think the acceptance criteria should include "given a labware identifier find the associated positive or negative control batch" ?
> 
> To clarify, is this any labware in the pipeline or a specific plate at a specific point of the pipeline?

Thanks, added that to the acceptance criteria. I guess it's any labware that might have a tracked reagent associated with it. I'm in the process of getting a full list of the reagents they want to track so hopefully that will help.

**Comment by JamesGlover** [comment]
The plate summaries page:
https://sequencescape.psd.sanger.ac.uk/plate_summaries/DN482431E
Already provides a nice overview of metadata associated with all labware in a given pipeline, and given a plate downstream in a pipeline, you should be able to link to this page.

**Comment by JamesGlover** [comment]
All this said though, I thought positive and negative controls got introduced prior to entry into limber during the initial Cherrypick process. Addressing that would probably require Beckman involvement

**Comment by KatyTaylor** [comment]
> The plate summaries page: https://sequencescape.psd.sanger.ac.uk/plate_summaries/DN482431E Already provides a nice overview of metadata associated with all labware in a given pipeline, and given a plate downstream in a pipeline, you should be able to link to this page.

Yeah this page is very relevant for this OKR - definitely along the right lines. Do you know what the 'Metadata' box on the top right of the screen is meant to contain? Don't think any of the ones I've clicked on have had anything there.

**Comment by KatyTaylor** [comment]
> All this said though, I thought positive and negative controls got introduced prior to entry into limber during the initial Cherrypick process. Addressing that would probably require Beckman involvement

Yeah these ones might need thinking about differently. I wrote a summary previously of how they work currently in the final comment on this page - https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Cardinal+Controls
