### ISSUE TITLE
[2nd August] DPL-395-1 Track external batches (input)

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1114]
**User story**
As a member of the Heron team, I would like to track external reagent / equipment batch numbers in the LIMS. This will benefit us because:
- Less work for lab team - can stop recording external reagent batch numbers in paperwork (14 in total)
- Better data integrity due to less manual recording of information (can scan instead of type if it’s a barcode; even if it’s not a barcode then there is no handwriting ambiguity)
- Can investigate relationships between external batches and plates they were used on more quickly than currently
    - This is less important than for internally-produced batches as the bought batches are generally of high quality

**Who are the primary contacts for this story**
Barbora, @harrietc52 @KatyTaylor 

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] On a labware page in Limber, there is a list of whichever reagents are relevant to that plate (see table in additional context)
- [x] I can scan or type the batch numbers for the above into the LIMS and they are saved
- [x] Previously scanned and saved batch numbers are visible on their relevant labware page

**Dependencies**
https://github.com/sanger/sequencescape/issues/3630

**References**
This solution can also be used to track internally created batches for the time being. We have separate stories for those (https://github.com/sanger/General-Backlog-Items/issues/190, https://github.com/sanger/General-Backlog-Items/issues/191, https://github.com/sanger/General-Backlog-Items/issues/192), and there might be better ways to track them, this should work fine as a basic first version. 

Related story https://github.com/sanger/limber/issues/1034 describes the same technical solution (but without the 'search' requirement) - this was created earlier as an idea for recording some of the information from the paperwork / Trello - probably useful to read through for extra ideas about technical implementation.

**Additional context**
It might be useful to make a couple of wireframes to show Barbora or other stakeholders to verify this approach.

This only needs to be implemented for 384-well pipeline as they no longer use the 96-well pipeline.

Current situation:
- Various externally-created reagent batches are not tracked in the LIMS, but batch numbers are written in the paperwork.

**Comment by harrietc52** [comment]
# When ready for deployment

- [ ] Merge in Deployment branch https://github.com/sanger/deployment/pull/259
- [ ] Merge in Sequencescape https://github.com/sanger/sequencescape/pull/3640
- [ ] Merge in Limber
- [ ] Deploy Sequencescape
`ansible-playbook -vD deploy_sequencescape.yml -i environments/<env> -e "github_branch=xxx" -e "full_deploy=true reload_nginx=false skip_migrations=false with_quant_files=false"`
- [ ] Deploy Limber 
`ansible-playbook -vD deploy_limber.yml -i environments/<env> -e "github_branch=xxx" -e "full_deploy=true reload_nginx=false"`
