### ISSUE TITLE
DPL-443 - Add 'Enriched BCR and TCR' plate types to Bespoke PCR pipeline

### ISSUE THREAD

**Issue by stevieing** [sanger/limber#1130]
**User story**
As a bespoke user can a new plate type (purpose) be added to the ‘Limber-Bespoke-PCR’ family of processes – this would be an ‘enriched TCR’ and ‘enriched BCR’ for any TCR and BCR library types (including HT variants) that were processed manually

**Who are the primary contacts for this story**
Matt M

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Version of the Bespoke PCR pipeline exists, where a 'LBB Enriched BCR' plate is between the 'LBB Cherrypick' and 'LBB Ligation' plates. The only library type with this option is 'Manual Chromium single cell BCR' (added in [DPL-442](https://github.com/sanger/limber/issues/1129))
- [ ] Version of the Bespoke PCR pipeline exists, where a 'LBB Enriched BCR HT' plate is between the 'LBB Cherrypick' and 'LBB Ligation' plates. The only library type with this option is 'Manual Chromium single cell BCR HT' (added in [DPL-442](https://github.com/sanger/limber/issues/1129))
- [ ] Version of the Bespoke PCR pipeline exists, where a 'LBB Enriched TCR' plate is between the 'LBB Cherrypick' and 'LBB Ligation' plates. The only library type with this option is 'Manual Chromium single cell TCR' (added in [DPL-442](https://github.com/sanger/limber/issues/1129))
- [ ] Version of the Bespoke PCR pipeline exists, where a 'LBB Enriched TCR HT' plate is between the 'LBB Cherrypick' and 'LBB Ligation' plates. The only library type with this option is 'Manual Chromium single cell TCR HT' (added in [DPL-442](https://github.com/sanger/limber/issues/1129))
- [ ] The original version, without the 'enriched' plates, also exists for all these library types.

**Dependencies**
This story is blocked by the following dependencies:
- https://github.com/sanger/limber/issues/1129

**Comment by andrewsparkes** [comment]
Current pipeline for TCR (BCR simillar):
LBC Cherrypick
LBC TCR Dil 1
LBC TCR Enrich1 2XSPRI
LBC TCR Enrich2 2XSPRI
LBC TCR Dil 2
LBC TCR Post Lig 1XSPRI
LBC TCR Post PCR

Not sure where the new plate types fit in there (which is the ligation/pcr plate?), would like the full list of what the new ones are called and their existing equivalents.
Should be just a configuration addition to define the new plate purposes and pipeline relationships. Small effort.

**Comment by andrewsparkes** [comment]
So 4 new plate types 4 library types for HT and not

**Comment by andrewsparkes** [comment]
LBB Enriched BCR
LBB Enriched BCR HT
LBB Enriched TCR
LBB Enriched TCR HT
