### ISSUE TITLE
DPL-459 Clean up pipeline grouping

### ISSUE THREAD

**Issue by harrietc52** [sanger/limber#1150]
**User story**
As Liz E, I would like to add more pipeline "groups" to the WIP Kanban views to better see related labware together. 

**Who are the primary contacts for this story**
@KatyTaylor 
@harrietc52 

**Who is the nominated tester for UAT**
Liz E

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Check below questions
- [ ] Update groupings to the below

**Dependencies**
This story is blocked by the following dependencies:
- Add filter to Kanban [DPL-458](https://github.com/sanger/limber/issues/1149) 

**Additional context**

- [ ] Liz to confirm `Chromium` pipeline grouping: v3/5p/BCR/TCR pipelines (Q: check would filter on library type work?)
- [ ] `PCR`: confirm what to do (currently bit of a catch all)
- [ ] `LB Lib Pool Norm` - output for nearly all pipelines so is it useful to have in all pipeline groups? Could it be removed if it isn't useful for any as it is in all
- [ ] Group: `Custom Pool` group
- [ ] Group: Targeted NanaSeq pipelines
- [ ] Group: WGS and pWGS
- [ ] Archive: GnT/scRNA will hopefully be getting "sunset" in September 
- [ ] Q: Multiplex pipeline to be group? (Q: have they all different library types?)
