### ISSUE TITLE
DPL-098 - As Scott I need to do a Lysate plate consolidation for the Combined LCM DNA / RNA-seq pipeline [ToR 12]

### ISSUE THREAD

**Issue by stevieing** [sanger/limber#786]
**User story**
As Scott I need to do a Lysate plate consolidation for the Combined LCM DNA / RNA-seq pipeline

**Who are the primary contacts for this story**
Scott / Steve

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Scan up to 4 source plates
- [ ] Transfer all the samples from sources into 2 plates (DNA and RNA) as described in https://docs.google.com/document/d/1s5AvMllBHZzMpx85simlCivBSmnfctJ5cwl_AXJFF5I/edit
- [ ] Validate wireframe with users

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by stevieing** [comment]
Plates coming into the process are of laser-capture microdissected tissue samples in lysis buffer in 96-well PCR plates. The nature of this step means that at most 24 wells of the plate will be filled due to the length of time it takes to capture a tissue sample in each well; more samples than this may lead to samples degrading. We are enforcing the same sample layout on all plates going into the process; samples will be present in wells A1-H3. So the very first thing that needs to happen before anything else is a consolidation of up to four of these partially filled plates into a single 96 well plate.

**Comment by harrietc52** [comment]
[Combined.LCM.DNA-.RNA-seq.pdf](https://github.com/sanger/limber/files/6930115/Combined.LCM.DNA-.RNA-seq.pdf)

**Comment by JamesGlover** [comment]
Details in the google doc:
https://docs.google.com/document/d/1s5AvMllBHZzMpx85simlCivBSmnfctJ5cwl_AXJFF5I/edit

**Comment by JamesGlover** [comment]
Unfortunately the 'simpler' behaviour means we can't just re-use the existing behaviour. Might be worth double checking if the fixed layout stamping is a requirement, or an attempt to simplify things for our benefit. Mostly I'm concerned about what the correct behaviour is in the event of plates with <24 wells. (Either due to failures or insufficient material)

If they are happy with the existing consolidation behaviour, then this is just configuration.

**Comment by JamesGlover** [comment]
Background:
Existing consolidation plate config:
```
# This configuration file is for the Bespoke Chromium Aggregation pipeline.
# LBC Stock plates are submitted to the Aggregation pipeline to be combined
# through LBC Aggregate plates into LBC Cherrypick plates.
# LBC Cherrypick plates can be submitted to various Chromium 10X automated
# pipelines for library preparation.
---
LBC Aggregate:
  :asset_type: plate
  :creator_class: LabwareCreators::TenStamp
  :file_links: []
LBC Cherrypick:
  :asset_type: plate
  :creator_class: LabwareCreators::TenStamp
  :state_changer_class: StateChangers::AutomaticPlateStateChanger
  :work_completion_request_type: 'limber_bespoke_aggregation'
  :file_links:
  - name: 'Download Hamilton Aggregate Cherrypick CSV'
    id: 'hamilton_aggregate_cherrypick'
  - name: Download Concentration (ng/ul) CSV
    id: concentrations_ngul
```

**Comment by JamesGlover** [comment]
`LabwareCreators::TenStamp` is a subclass of `LabwareCreators::MultiStamp` The key new behaviour seems to be the `self.transfers_layout = 'sequential'` configuration, which determines how source plats map to the destination. We'll need a new creator class with a different transfers_layout setting, and a new layout configured in `app/javascript/shared/transfersLayouts.js`

**Comment by JamesGlover** [comment]
The volume behaviour of the `LabwareCreators::TenStamp` class probably isn't strictly needed here, as we aren't generating CSVs, but it shouldn't harm.

**Comment by JamesGlover** [comment]
Also, see: https://github.com/sanger/limber/issues/787 As there's the possibility we'll be needing to register two shildren in this plate creator.

**Comment by JamesGlover** [comment]
Communication chain:

> Hello Scott and SSRs (Steve CCed),
>  
> GPL-098 and GPL-099 as part of delivering the LBM DNA/RNA pipelines have been prioritised, but I’d like to clarify the requirements slightly:
>  
> The stories are:
>  
> DPL-098 - As Scott I need to do a Lysate plate consolidation for the Combined LCM DNA / RNA-seq pipeline
> https://github.com/sanger/limber/issues/786
>  
> DPL-099 As Scott after Lysate Plate Consolidation I need to split of the total volume of lysate in each well (50ul) into two equal 25ul fractions on different plates
> https://github.com/sanger/limber/issues/787
>  
> From the process map it appears that the consolidation onto the ‘Cherrypick?’ plate, and the subsequent stamp out onto the RNAseq cherrypick and DNAseq cherrypick plates happens on the bravo as a single step.
>  
> 1)      Scott: Is there a desire to track the intermediate Cherrypick plate, or could this remain untracked? Generally if a plate never leaves the robot, and doesn’t need to be stored, there isn’t a huge amount of value in tracking it.
> a.      Tracked workflow
> Scan in a source plate > Click ‘Create Cherrypick? Plate’ > Scan in additional source plates > Click ‘Create  RNAseq cherrypick plate’ > Click ‘RDAseq cherrypick’ > Robot verify with all 7 plates
> b.      Untracked workflow
> Scan in a source plate > Click ‘Create RNAseq/DNAseqPlates’ > Scan in additional source plates > Robot verify with 6 plates
>  
> 2)      SSRs: As there are effectively two different libraries being made, we need a request for both.
> Currently this would require two separate submissions for the untracked workflow, one for each library. Would this be acceptable?
>  
> For the tracked pipeline we run into more significant issues upfront, but it will probably be worth having a meeting to discuss that further if we find we need to go that route. Which SSRs are best placed to be involved in this discussion.
>  
> Best wishes,
>  
> James

SSR response:

> HI James,
>  
> From an SSR point of view I don’t think this will be a problem – will this be able to work like GnT sequencing where we are able to do both submissions within the same document just for a different library type ?
>  
> As an SSR contact point I’m more than happy to help as I am sure CASM will be a big user of this line , so it would make sense to help the development.
>  
> Please let me know if I can be any further help
>  
> Best Wishes
>  
> Maisie  

Scott response:

> Hi James,
> Yes, as you correctly determined the ‘Cherrypick?’ plate never leaves the robot, so if it’s easier to create the untracked workflow you mention and generate the DNAseq & RNAseq plates directly that’s absolutely fine with me.
>  
> Thanks,
> Scott G.

**Comment by JamesGlover** [comment]
The main advantages to *not* tracking the 'Cherrypick?' plate is it makes it *much* easier to handle the two library requests. It places the branch right at the beginning of the pipeline, meaning that there is no need for an aggregation request, and also that we will not need to change the submission builder to handle branching submissions. The main reason for proposing the aggregation request, is otherwise the aliquots on the cherrypick? plate would be associated with two requests. The alternative, a migration to a many-many relationship, would be a challenge, and would have performance considerations due to the additional joins and insertions. 

The untracked approach does mean that you'd probably want to spit out both the RNA and DNA plates at this stage, otherwise there is repetition when scanning in the layouts, and it would be easy to make a mistake and not use the same layout each time.

**Comment by emrojo** [comment]
** Tasks **
- [ ] Create wireframe about the process with SS and Limber about the consolidation + 2 plates creation (DNA and RNA)
- [ ] Create transfer layout as described in https://docs.google.com/document/d/1s5AvMllBHZzMpx85simlCivBSmnfctJ5cwl_AXJFF5I/edit
- [ ] Create plate creator to handle creation of both destination plates (DNA and RNA) in one click

**Comment by emrojo** [comment]
Possibly it could require:

* 2 Library types (DNA and RNA)
* 1 Submission Template (they will create 2 submissions in each source, one for DNA and one for RNA)
* 1 Request Type

**Comment by emrojo** [comment]
Reply to wireframe from Scott G.
```
-          What is the name for the new 2 library types required (for DNA and RNA)
Combined LCM DNA, Combined LCM RNA
-          What is the name for the submission template? (we defined temporarily Limber-LCM DNA / RNA-seq)]
Limber-Combined LCM DNAseq/RNAseq
-          What is the product catalogue?
Not sure what is meant by this (sorry)
-          What is the product line?
o   Options : Illumina A, IlluminaB, IlluminaC, Illumina http, Bespoke
Should be able to go down the same line as the current LCM pipeline?
-          What is the name of the plate purposes? We defined this:
o   Lysate LCA
o   Lysate DNAseq cherrypick
o   Lysate RNAseq cherrypick
I don’t know if there are any particular rules regarding plate names, but the following makes more sense to me:
Lysate LCM
Consolidated lysate DNAseq
Consolidated lysate RNAseq
 
One final thing I might add based on looking at the wireframe is juts to clarify that the lysate consolidation is happening on a Bravo, not a Hamilton as shown in the wireframe.
```
