### ISSUE TITLE
DPL-235 - Heron pipeline improvements - Investigate how we can track plates more effectively

### ISSUE THREAD

**Issue by stevieing** [sanger/limber#973]
**Description**
Heron pipeline improvements - Investigate how we can track plates more effectively. We are currently using Trello which is slow, time consuming and manual.

**Who the primary contacts are for this work**
Sara / Steve

**Task tracking**
- [x] Fix current Limber 'work in progress' / kanban view (https://github.com/sanger/limber/issues/994)
- [x] Investigate similar requirements from DNAP
- [x] Investigate Mini LIMS as an option
- [x] Come up with options for metadata requirement
- [ ] Come up with next actions

**Comment by stevieing** [comment]
**Notes from meeting with Sara (02/02):**
- Heron need to know that they have done everything they should have done
- Issue noticed recently where 6 plates were found in the freezer which hadn't been processed. It was too late
- Currently using Trello to track plates. This is a manual process
- Need functionality to allow them to track plates from start to finish with all of the stages where a new barcode is created
- Also need to be able to archive plates
- Ideally would like this to be integrated with LIMS

**Next steps:**
- Sara will provide access to the Trello board
- sara will provide simple requirements for plate tracking
- PSD will create a research story for the best options

**Out of scope:**
- reagent aliquots
- removing need for paperwork - the Heron team currently create a lot of paperwork which is archived manually. They would ideally like to record this data against plates

**Comment by stevieing** [comment]
Re: Trello
https://developer.atlassian.com/cloud/trello/rest/api-group-cards/#api-group-cards
You can create cards (e.g. we could create their 96-well cherrypick plates).
You can update and delete cards.
We could therefore auto-create the cherrypick plate cards on the trello board at the point of creating those plates in the LIMS, then after quad stamping to 384 create the 384-well plate cards on the trello board, link the original 96-well cards to them and archive the 96s.
In theory we could also do a similar process for each plate step they want to track. moving their cards across the board for them.
Linking to an external service (Trello) may not be straight-forward.
Also Trello is owned by Atlassian, it does integrate with Confluence (and Jira). (edited) 

[emr](https://app.slack.com/team/U0ABUF6NL)  [3:07 PM](https://psd-team.slack.com/archives/G016NFY23SL/p1643814466453169)
maybe we could like 'validate' the trello board?
[3:08](https://psd-team.slack.com/archives/G016NFY23SL/p1643814481208729)
like autocomplete with what we have

[Andrew](https://app.slack.com/team/UB93KB3TQ)  [3:17 PM](https://psd-team.slack.com/archives/G016NFY23SL/p1643815065298709)
For 'pre-planning' which 96s would be combined into 384s: That's the quad stamp page in Limber where you say this 96 will go in quadrant 1 of the 384, this one in quadrant 2 etc. Guess we could have the 2nd column on the board be for 'pending' transfers. Use quad stamp in Limber, we auto-move the 96s across into the 'pending transfers' column and update each card in the set of 4 to indicate the grouping, then archive the 96 cards and create the 384 card in the next column once the 384 is state 'passed' in Limber.

[1 reply](https://app.slack.com/client/T0AAUQ057/G016NFY23SL/thread/C01J32MB747-1643907732.339739)
1 day agoView thread

[Andrew](https://app.slack.com/team/UB93KB3TQ)  [3:18 PM](https://psd-team.slack.com/archives/G016NFY23SL/p1643815100275779)
Still feels like Limber should have this visualisation functionality (by pipeline) though doesn't it.

[Katy](https://app.slack.com/team/UPELQJYA2)  [4:26 PM](https://psd-team.slack.com/archives/G016NFY23SL/p1643819163695019)
Yeah feels like we could have a dual strategy of:
Make their lives better quickly(ish) by autocreating some of the Trello cards - maybe just the first one or two columns
Keep improving the Kanban page until it's good enough to switch them over to

**Comment by stevieing** [comment]
This story is on hold awaiting the requirements frm Sara.

**Comment by KatyTaylor** [comment]
Requirements from Sara (sent 11/02/2022):

**Current Problem statement**
 
In order to track the 700 x 96w plates and 175 x 384w plates produced in the Heron lab every week, we currently manually transcribe the plate barcodes to Trello cards, with other pertinent information.  We then manually move these through the various Library prep processes until they are released for the sequencing process. Example of Post-PCR Trello board below (every card is archived, so we currently have 11 Trello boards – 2 live boards and 9 archive boards).
Alongside this, we use Limber to produce our barcodes, track our plates through the workflow, cancel and rework plates, and for robot bed verification.
We also produce 5 pages of worksheet data for every 384w plate to capture information important for quality assurance, which is then scanned and attached to each Trello card (and also stored in paper form in archive boxes in our office).
 
(image of Trello board was meant to be here - we have links to the live version instead)
 
**Requirements for replacement of Trello for tracking Heron plates**
 
In order of priority:
 
1. _The ability to visualise the plates moving through the Heron process by way of an automated Kanban-style board which is linked to LIMBER with the view to replace the manual Trello boards used._
    a. We  would like to eliminate the need for manual transcription of plate barcodes into a different system, when plate information is already present in Limber/SeqScape.
    b. We would like the ability to see that all 96w plates have been combined into a 384w plate for library prep.
    c. We would like to see all steps in the library prep process on the Kanban board including the two tube steps (LTHR-384 Pool XP and LB Lib Pool Norm) at the end of the process.
    d. If there is a lab error and the team need to go back to the previous step in the process to repeat, they are able to do that on LIMBER. We would like to have a flag to highlight that the plate is ‘on hold’ until a team lead is able to deal with the rework.  When the plate is ‘failed’ or ‘cancelled’ we would like for it to no longer appear on the board, rather than having to manually remove from the board.  If this is not possible and the plate on which the error happens does remain on the Kanban board, we would like to add a flag that appears if a plate has been at certain stage for 1 week. This would then allow the lab team to routinely go through and clean up the board.
 
 
2. _Remove the need to manual plate paperwork, with the cards capturing all the information that the lab worksheets currently do._
    a. We would like to capture information currently on the lab worksheet in electronic form.  This would include: robots used (already in Limber for bed verification in many parts), control/aliquot batches (these would need barcodes), ability to free text lot numbers for some reagents used, buddy check/witness initials at points.
    b. We would like Expandable “cards” – currently the Kanban shows the plate ID and date created, as well as ID of the plate on which the submission was made – this stays with the card throughout the process as the card moves along the Kanban and gets a new unique ID for each stage. It also has a link to the plate on LIMBER. We would like to be able to click on the card which would then enlarge and show all the information associated with that plate similar to Trello and the summary page on SS.
    c. In order to replace the physical paperwork we would need to retain the completed cards in case a plate needs to be reviewed for an investigation or any other reason. We would like the cards to be moved to an archive area where they can remain indefinitely and reviewed using a series of filters (plate ID, specific date or date range, robot used, plate purpose (step of the process), control batch, etc).

**Comment by KatyTaylor** [comment]
Outputs from this are:
- Stories under the 'Plate tracking' label (DPL-322 -> DPL-329)
- Research doc here - https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/r.+Heron+pipeline+improvements+-+Investigate+how+we+can+track+plates+more+effectively

I've emailed Sara, Emma and Liz E with these stories - next step is to identify the best ones to do first.

**Comment by KatyTaylor** [comment]
Closing, as is in Done column.
